Refactor codegen to target more backends

diff --git a/contrib/plot-elf-galore.yaml b/contrib/plot-elf-galore.yaml
--- a/contrib/plot-elf-galore.yaml
+++ b/contrib/plot-elf-galore.yaml
@@ -15,26 +15,65 @@ artifacts:
     type: inline
     data: |
       id
-  elf1:
+      sleep 0.25
+      for x in c; do
+        cat /tmp/sh4d0wup-test-$x.log || echo "test failed: $x"
+      done
+      echo all tests completed
+
+  # it's not possible to execute scripts through memfd because the interpreter can't open the in-memory file descriptor
+  # for this reason we wrap it in another elf
+  payload-elf:
     type: infect
     infect: elf-fwd-stdin
     artifact: payload
-  elf-decoy:
+
+  test-c-done:
     type: infect
     infect: elf-fwd-stdin
-    data: 'echo :3'
-  elf2:
+    backend: c
+    data: |
+      echo 'test complete: c' > /tmp/sh4d0wup-test-c.log
+  #test-go-done:
+  #  type: infect
+  #  infect: elf-fwd-stdin
+  #  backend: go
+  #  data: |
+  #    echo 'test complete: go' > /tmp/sh4d0wup-test-go.log
+  #test-rust-done:
+  #  type: infect
+  #  infect: elf-fwd-stdin
+  #  backend: rust
+  #  data: |
+  #    echo 'test complete: rust' > /tmp/sh4d0wup-test-rust.log
+
+  test-bind-c:
     type: infect
     infect: elf
-    artifact: elf1
-  elf3:
+    backend: c
+    artifact: payload-elf
+    elf_artifact: test-c-done
+  #test-bind-go:
+  #  type: infect
+  #  infect: elf
+  #  backend: go
+  #  artifact: test-bind-c
+  #  elf_artifact: test-go-done
+  #test-bind-rust:
+  #  type: infect
+  #  infect: elf
+  #  backend: rust
+  #  artifact: test-bind-go
+  #  elf_artifact: test-rust-done
+
+  # wrap one last time so there's a stable artifact name we can reference
+  elf:
     type: infect
     infect: elf
-    artifact: elf1
-    elf_artifact: elf-decoy
+    artifact: test-bind-c
 
 routes:
   - path: /a
     type: static
     args:
-      artifact: elf3
+      artifact: test-bind-c
